<?

    $broker_list = array(
        array("AAB", "Kreditbanken A/S"),
        array("AAL", "Ålandsbanken Abp"),
        array("ABC", "ABG Sundal Collier Norge ASA"),
        array("ABLV", "ABLV Bank, AS"),
        array("ABS", "Ålandsbanken Abp"),
        array("AEE", "Algo Engineering Europe Ltd."),
        array("AIV", "Aktieinvest FK AB"),
        array("ALB", "Arbejdernes Landsbank A/S"),
        array("ALM", "Alm. Brand Bank A/S"),
        array("AOI", "All Options International B.V."),
        array("APK", "Euroclear Finland Oy"),
        array("ARB", "Arion banki hf."),
        array("ARC", "Arctic Securities ASA"),
        array("ARF", "Arctica Finance hf."),
        array("ASC", "ABG Sundal Collier Norge ASA"),
        array("ATP", "ATP Fondsmæglerselskab A/S"),
        array("AUD", "Audur Capital hf."),
        array("AVA", "Avanza Bank AB"),
        array("BANO", "BankNordik P/F"),
        array("BAS", "Basisbank A/S"),
        array("BBB", "Joh. Berenberg, Gossler & Co. KG"),
        array("BPA", "BNP Paribas Arbitrage"),
        array("BPP", "BNP Paribas Arbitrage SNC"),
        array("BRC", "Barclays Capital Securities Limited Plc"),
        array("BRF", "BRFkredit A/S"),
        array("BSP", "Brørup Sparekasse"),
        array("CA", "Carnegie ASA"),
        array("CAD", "Carnegie Investment Bank AB"),
        array("CAM", "Carnegie Asset Management"),
        array("CAN", "Carnegie AS"),
        array("CAR", "Carnegie Investment Bank AB"),
        array("CBA", "Carnegie Bank A/S"),
        array("CBK", "Commerzbank AG"),
        array("CDG", "Citadel Securities (Europe) Limited"),
        array("CDV", "Crédit Agricole Cheuvreux Nordic AB"),
        array("COAAB", "Kreditbanken A/S"),
        array("COALB", "Arbejdernes Landsbank A/S"),
        array("COALM", "Alm. Brand Bank A/S"),
        array("COALO", "ALOC Bonnier A/S"),
        array("COAMA", "Amagerbanken af 2011 A/S"),
        array("COATP", "ATP Fondsmæglerselskab A/S"),
        array("COBANO", "BankNordik P/F"),
        array("COBAS", "Basisbank A/S"),
        array("COBEC", "Bankernes EDB Central"),
        array("COBEH", "Bankernes EDB Central, Herning"),
        array("COBER", "Bankernes EDB Central, Roskilde"),
        array("COBKD", "Bankdata"),
        array("COBRF", "BRFkredit A/S"),
        array("COBSP", "Brørup Sparekasse"),
        array("COCAM", "Carnegie Asset Management"),
        array("COCBA", "Carnegie Bank A/S"),
        array("COCPH", "NASDAQ OMX Copenhagen"),
        array("CODAB", "Danske Andelskassers Bank A/S"),
        array("CODDB", "Danske Bank A/S"),
        array("CODEX", "Dexia Bank Denmark A/S"),
        array("CODIF", "SAXO E*BANK"),
        array("CODIS", "DiBa Bank"),
        array("CODJU", "Djurslands Bank A/S"),
        array("CODLR", "DLR Kredit A/S"),
        array("CODRO", "Dronninglund Sparekasse"),
        array("COEGH", "ebh bank A/S"),
        array("COEIK", "Sparekassen Lolland A/S"),
        array("COEIKB", "Sparekassen Lolland A/S"),
        array("COENO", "Nordjyske Bank"),
        array("COFAR", "Sparekassen Farsø"),
        array("COFIH", "FIH Erhvervsbank A/S"),
        array("COFII", "FIH Erhvervsbank A/S"),
        array("COFIT", "Finanstilsynet"),
        array("COFRO", "Frøs Herreds Sparekasse"),
        array("COFSP", "Eik Banki P/F"),
        array("COFST", "Finansstyrelsen"),
        array("COGRL", "Grønlandsbanken A/S"),
        array("COHAB", "Max Bank af 2011 A/S"),
        array("COHAM", "Sparekassen Hammel"),
        array("COHHS", "Hvetbo Herreds Sparekasse"),
        array("COHIM", "Sparekassen Himmerland"),
        array("COHOB", "Sparekassen Hobro"),
        array("COHVI", "Hvidbjerg Bank A/S"),
        array("COJEL", "Jelling Sparekasse"),
        array("COJYB", "Jyske Bank A/S"),
        array("COJYS", "Den Jyske Sparekasse"),
        array("COKOA", "Københavns Andelskasse"),
        array("COKOM", "KommuneKredit"),
        array("COKRO", "Sparekassen Kronjylland"),
        array("COKTF", "Kaupthing Føroyar Fondsmæglerselskab"),
        array("COLAS", "Lån & Spar Bank A/S"),
        array("COLDM", "Maj Invest Markets"),
        array("COLOB", "Lollands Bank A/S"),
        array("COLOL", "Sparekassen Lolland"),
        array("COLPB", "Lægernes Pensionsbank"),
        array("COLSP", "Løkken Sparekasse"),
        array("COMABA", "Max Bank af 2011 A/S"),
        array("COMNB", "Møns Bank A/S"),
        array("COMOR", "Morsø Bank A/S"),
        array("COMOS", "Fjordbank Mors"),
        array("CONAT", "Danmarks Nationalbank"),
        array("CONDA", "Nordea Bank Danmark A/S"),
        array("CONDF", "Nordea Bank Finland Plc"),
        array("CONEB", "Sparekassen for Nr. Nebel og Omegn"),
        array("CONFY", "Nordfyns Bank A/S"),
        array("CONIM", "Nordea Investment Management AB, Denmark"),
        array("CONOA", "Nordea Bank Danmark A/S"),
        array("CONRS", "Nørresundby Bank A/S"),
        array("CONSP", "Nordoya Sparikassi"),
        array("CONYB", "Nykredit Bank"),
        array("CONYK", "Nykredit A/S"),
        array("COOJB", "Østjydsk Bank A/S"),
        array("COPSB", "Pen-Sam Bank A/S"),
        array("CORDD", "Realkredit Danmark A/S"),
        array("CORIL", "Ringkjøbing Landbobank A/S"),
        array("CORIS", "Rise Spare- og Lånekasse"),
        array("COROS", "Roskilde Bank A/S"),
        array("COSAL", "Salling Bank A/S"),
        array("COSAX", "Saxo Bank A/S"),
        array("COSDC", "Sparekasssernes Data Center"),
        array("COSEE", "Skandinaviska Enskilda Banken A/S"),
        array("COSEM", "SEB Merchant Banking"),
        array("COSKA", "Sparekassen i Skals"),
        array("COSKJ", "Skjern Bank A/S"),
        array("COSNB", "Spar Nord Bankaktieselskab"),
        array("COSPA", "Sparinvest Fondsmæglerselskab A/S"),
        array("COSPF", "Sparekassen Faaborg"),
        array("COSPLO", "Sparekassen Lolland A/S"),
        array("COSPM", "Middelfart Sparekasse"),
        array("COSPSJ", "Sparekassen Sjælland A/S"),
        array("COSPV", "Sparekassen Sjælland"),
        array("COSVB", "Svenska Handelsbanken (filial)"),
        array("COSVS", "Svendborg Sparekasse"),
        array("COSYD", "Sydbank A/S"),
        array("COTHY", "Sparekassen Thy"),
        array("COTND", "Tønder Bank A/S"),
        array("COTOK", "Totalkredit Realkreditfond"),
        array("COTOT", "Totalbanken A/S"),
        array("COUKR", "Unikredit Realkreditaktieselskab"),
        array("COVEF", "Vestfyns Bank A/S"),
        array("COVES", "Sparbank"),
        array("COVHS", "Vorbasse Hejsnvig Sparekasse"),
        array("COVIN", "Vinderup Bank A/S"),
        array("COVJB", "Vestjysk Bank A/S"),
        array("COVOR", "Vordingborg Bank A/S"),
        array("COVP", "Værdipapircentralen"),
        array("COVRA", "Sparekassen Vendsyssel"),
        array("COXAA", "Aarhus Lokalbank Aktieselskab"),
        array("COXFA", "Faster Andelskasse"),
        array("COXFK", "Andelskassen Fælleskassen"),
        array("COXLK", "Lunde-Kvong Andelskasse"),
        array("COXLR", "LR Realkredit A/S"),
        array("CRE", "Cresco Väärtpaberid"),
        array("CSA", "Christiania Securities AS"),
        array("CSB", "Credit Suisse Securities (Europe) Ltd"),
        array("CSD", "Københavns Fondsbørs DataWarehouse"),
        array("CSE", "Nasdaq OMX Copenhagen"),
        array("CTD", "Citadele banka AS"),
        array("DAB", "Danske Andelskassers Bank A/S"),
        array("DBL", "Deutsche Bank AG"),
        array("DDB", "Danske Bank A/S"),
        array("DDBE", "Danske Bank A/S Eesti filiaal"),
        array("DDBL", "Danske Bank A/S Lietuvos filialas"),
        array("DDE", "Hembanken"),
        array("DEX", "BIL Bank Danmark A/S"),
        array("DIF", "SAXO Privatbank A/S"),
        array("DIS", "DiBa Bank"),
        array("DJU", "Djurslands Bank A/S"),
        array("DLR", "DLR Kredit A/S"),
        array("DNBR", "DNB banka"),
        array("DNBV", "DNB Bankas AB"),
        array("DNM", "DNB Bank ASA"),
        array("DRO", "Dronninglund Sparekasse"),
        array("DRS", "Commerzbank AG"),
        array("EGH", "ebh bank A/S"),
        array("ELR", "Endurlán ríkissjóðs"),
        array("ENO", "Nordjyske Bank"),
        array("ENS", "Skandinaviska Enskilda Banken AB"),
        array("EPB", "Erik Penser Bankaktiebolag"),
        array("ESO", "SEB Enskilda ASA"),
        array("EVL", "Evli Bank Abp"),
        array("FAR", "Sparekassen Farsø"),
        array("FBI", "Bankas Finasta AB"),
        array("FBK", "BankNordik P/F"),
        array("FE", "Fearnley Fonds ASA"),
        array("FIH", "FIH Erhvervsbank A/S"),
        array("FII", "FIH Erhvervsbank A/S"),
        array("FIM", "FIM Bank Ltd"),
        array("FLW", "Flow Traders B.V."),
        array("FNB", "Finbaltus FMI UAB"),
        array("FOF", "Fondsfinans ASA"),
        array("FOR", "ABN AMRO Clearing Bank N.V."),
        array("FORC", "ABN AMRO Clearing Bank N.V."),
        array("FORL", "ABN AMRO Clearing Bank N.V."),
        array("FORU", "ABN AMRO Clearing Bank N.V."),
        array("FRO", "Frøs Herreds Sparekasse"),
        array("FSE", "First Securities AS"),
        array("FSP", "Eik Banki P/F"),
        array("FST", "Finansstyrelsen"),
        array("GEL", "GETCO Europe Limited"),
        array("GPC", "GPC"),
        array("GRL", "Grønlandsbanken A/S"),
        array("GSI", "Goldman Sachs International"),
        array("GTM", "Garantum Fondkommission"),
        array("HAM", "Sparekassen Hammel"),
        array("HBC", "HSBC Bank plc"),
        array("HCT", "Hardcastle Trading AG"),
        array("HEABR", "ABR Financial B.V"),
        array("HEAPK", "Euroclear Finland Oy"),
        array("HEBRC", "Barclays Capital Securities Limited Plc"),
        array("HEEVL", "Evli Bank Abp"),
        array("HEFIM", "FIM Bank Ltd"),
        array("HEFSA", "Financial Supervision Authority (Finl)"),
        array("HEHEL", "NASDAQ OMX Helsinki"),
        array("HENRD", "Nordea Bank Finland Plc"),
        array("HEUB", "UB Securities Ltd"),
        array("HEUOC", "Unidentified off-exchange counterparty"),
        array("HEX", "Nasdaq OMX Helsinki"),
        array("HFV", "H.F. Verðbréf hf."),
        array("HHS", "Hvetbo Herreds Sparekasse"),
        array("HIM", "Sparekassen Himmerland"),
        array("HIP", "Hipoteku banka"),
        array("HOB", "Sparekassen Hobro"),
        array("HSE", "Helsinki Stock Exchange"),
        array("HVI", "Hvidbjerg Bank A/S"),
        array("IAT", "International Algorithmic Trading GmbH"),
        array("IBR", "RSE Internet Broker"),
        array("ICE", "NASDAQ OMX Iceland hf."),
        array("IFJ", "Íslenskir fjárfestar"),
        array("IMA", "IMC Trading B.V."),
        array("IMC", "IMC Trading B.V."),
        array("INT", "Instinet Europe Limited"),
        array("ISB", "Íslandsbanki hf."),
        array("IVE", "Íslensk verðbréf hf."),
        array("JEF", "Jefferies International Limited"),
        array("JEL", "Jelling Sparekasse"),
        array("JPM", "J.P. Morgan Securities plc"),
        array("JVB", "Jöklar-Verðbréf hf."),
        array("JYB", "Jyske Bank A/S"),
        array("JYS", "Den Jyske Sparekasse"),
        array("KEM", "Knight Capital Europe Ltd"),
        array("KOA", "Københavns Andelskasse"),
        array("KOM", "KommuneKredit"),
        array("KRO", "Sparekassen Kronjylland"),
        array("KTF", "Kaupthing Føroyar Fondsmæglerselskab"),
        array("LAI", "Landsbankinn hf."),
        array("LAS", "Lån & Spar Bank A/S"),
        array("LAV", "Valo Research and Trading"),
        array("LDM", "Maj Invest Markets"),
        array("LFB", "Länsförsäkringar Bank AB"),
        array("LHV", "LHV Pank AS"),
        array("LOB", "Lollands Bank A/S"),
        array("LPB", "Lægernes Pensionsbank"),
        array("LSP", "Løkken Sparekasse"),
        array("LVG", "Latvijas valsts kase"),
        array("MABA", "Max Bank af 2011 A/S"),
        array("MCF", "ABN AMRO EMCF"),
        array("MEG", "Virðing hf."),
        array("MGF", "Mangold Fondkommission AB"),
        array("MLI", "Merrill Lynch International"),
        array("MMX", "MMX Trading B.V"),
        array("MNB", "Møns Bank A/S"),
        array("MOR", "Morsø Bank A/S"),
        array("MOS", "Fjordbank Mors af 2011 A/S"),
        array("MPB", "MP Banki hf."),
        array("MSI", "Morgan Stanley & Co. International plc"),
        array("MUL", "SMP Bank"),
        array("NAT", "Danmarks Nationalbank"),
        array("NB", "Norges Bank"),
        array("NCAAA", "AAA testmedlem"),
        array("NCAAKH", "Aust-Agder Energi Prod AS - Kraf"),
        array("NCAAKS", "Aust-Agder Energi Prod AS - Kund"),
        array("NCAAS", "Einar Aas"),
        array("NCABCA1", "UBS Clearing & Execution Service"),
        array("NCABCA2", "UBS Clearing & Execution Service"),
        array("NCACC", "N2EX DF Centrica Energy Limited"),
        array("NCADS", "Alpiq Eurotrade S.a.r.l"),
        array("NCAETR", "Akershus Energi Vannkraft AS"),
        array("NCAG", "Agder Energi AS"),
        array("NCAGA", "AGA AB"),
        array("NCAGAA", "AGA AB"),
        array("NCAGAB", "AGA AB"),
        array("NCAGD", "Vest-Agder Energiverk Energi AS"),
        array("NCAGMA", "LOS AS"),
        array("NCAGPR", "Agder Energi Produkjson AS"),
        array("NCAGR", "AGR Trading LLC"),
        array("NCAIR", "Air Liguide A/S"),
        array("NCAK", "Akershus Energi Vannkraft AS"),
        array("NCAKAH", "Akademiska Hus AB"),
        array("NCAKER", "Åkers Sweden AB"),
        array("NCALC", "Alfa Laval Corporate AB"),
        array("NCALF", "Alfa Kraft AB"),
        array("NCALF1", "Alfa Kraft 1"),
        array("NCALF2", "Alfa Kraft AB"),
        array("NCALP", "Alpiq Suisse SA"),
        array("NCALT", "Altia OY"),
        array("NCALV", "Älvsbyns Kommun"),
        array("NCAMF", "Amaranth LLC"),
        array("NCAMFP", "AMF Pensionförsäkring AB"),
        array("NCAPRI", "An Prima AB"),
        array("NCAQI", "Gaps Energy AS"),
        array("NCAQUA", "Aqua Holding AS"),
        array("NCARCT", "Arctic Paper Munkedals AB"),
        array("NCARFA", "Armada Bostäder AB"),
        array("NCARFO", "Arendals Fossekompani"),
        array("NCARHA", "Arctic Paper Håfreströms AB"),
        array("NCARO", "J. Aron & Company"),
        array("NCASCA", "Korsnäs Frövi AB"),
        array("NCASFR", "Korsnäs Frövi AB"),
        array("NCASG", "AssuranseService i Göteborg AB"),
        array("NCASKE", "Asker Kommune"),
        array("NCASTI", "Setra Trävaror AB"),
        array("NCASTO", "Aker Stord AS"),
        array("NCASU", "AssuranceService I Göteborg AB"),
        array("NCAT", "Alpiq Ltd."),
        array("NCATEL", "Alpiq Swisstrade Ltd."),
        array("NCATRI", "Atria Oyj"),
        array("NCAUST", "Austevoll Kraftlag BA"),
        array("NCAVIN", "Avinor AS"),
        array("NCAW", "Arise Windpower AB"),
        array("NCBAB", "Bergen Energi AB"),
        array("NCBABE", "Trafikverket"),
        array("NCBAC", "Jefferies Bache Ltd"),
        array("NCBAC-E", "Jefferies Bache LTD EXEC"),
        array("NCBAC-I", "Jefferies Bache Ltd AT"),
        array("NCBAC-P", "Jefferies Bache LTD-Prop"),
        array("NCBAC1", "Bache Commodities LTD"),
        array("NCBAEN", "Trafikverket"),
        array("NCBAER", "Baerum Kommune"),
        array("NCBAFO", "Trafikverket"),
        array("NCBAN", "Trafikverket"),
        array("NCBAS", "Barilla Sverige AB"),
        array("NCBAVE", "Trafikverket"),
        array("NCBC", "Barclays Bank Plc"),
        array("NCBE", "Bergen Energi Markets AS"),
        array("NCBEK", "Bekkestua Eiendom AS"),
        array("NCBEN", "Fortum Power & Heat AB"),
        array("NCBEP", "Baltic Energy Partners Oü"),
        array("NCBEST", "Bestkraft AB"),
        array("NCBGI", "BG International LTD"),
        array("NCBHF", "Deutsche Bank AG"),
        array("NCBHF1", "BHF-Bank - BHF1"),
        array("NCBHF2", "BHF-Bank - BHF2"),
        array("NCBHF3", "BHF-Bank - BHF3"),
        array("NCBHF4", "BHF-Bank - BHF4"),
        array("NCBHF5", "BHF-Bank - BHF5"),
        array("NCBHF6", "BHF-Bank - BHF6"),
        array("NCBHF7", "BHF-Bank - BHF7"),
        array("NCBINV", "Bjørgvin Invest AS"),
        array("NCBIR", "Fortum Energy Securities AB"),
        array("NCBIX", "Bixia AB"),
        array("NCBJER", "Bjerre og Lindskog Holding ApS"),
        array("NCBKK", "BKK Produksjon AS"),
        array("NCBKW", "N2EX DF BKW FMB Energie AG"),
        array("NCBNH", "BNH Invest AS"),
        array("NCBNPP", "BNP PARIBAS"),
        array("NCBOAB", "Bostads AB Vätterhem"),
        array("NCBOD", "Bodø Energi AS"),
        array("NCBOL", "Boliden Odda A/S"),
        array("NCBOR", "Borås Energi AB"),
        array("NCBOS", "Bostads AB VätterHem"),
        array("NCBOSA", "Midt-Telemark Energi AS"),
        array("NCBOV", "Bodycote Värmebehandling AB"),
        array("NCBP", "BP GAS Marketing Ltd."),
        array("NCBPGM", "BP"),
        array("NCBRAK", "Branden Kapital AS"),
        array("NCBRIN", "Brinch Trading AS"),
        array("NCBRIT", "N2EX DF British Gas Trading"),
        array("NCBRU", "Brukskraft AB"),
        array("NCBRV", "Bjørgvin Invest AS"),
        array("NCBTLA", "Schenker Property Sweden AB"),
        array("NCBTS", "Berendsen Textil Service AB"),
        array("NCBUF", "Nord Pool Trading BUF"),
        array("NCBUK", "EB Handel AS"),
        array("NCBUPR", "EB Kraftproduksjon AS"),
        array("NCBYGG", "Byggelit Aktiebolag"),
        array("NCCABP", "Coeli AB acting through Coeli Power"),
        array("NCCAR", "Cargill International SA"),
        array("NCCAT", "Cat Invest I AS"),
        array("NCCBK", "Nordea Bank Norge ASA"),
        array("NCCCM", "Carbon Capital Markets Ltd."),
        array("NCCEN", "Censu Trading AS"),
        array("NCCERE", "Svenska Lantmännen Ek.för."),
        array("NCCFCF", "CFP Energy Limited"),
        array("NCCFP", "CF Partners LLP"),
        array("NCCINN", "Cinnober Financial Technology AB"),
        array("NCCITA", "CITADEL ENERGY INVESTMENT LTD."),
        array("NCCITI", "Citigroup Global Markets Ltd"),
        array("NCCLW", "Cleanworld AS"),
        array("NCCNR", "N2EX DF Compagnie National du Rhône"),
        array("NCCO", "KE Marked AS"),
        array("NCCO2E", "CO2e.com"),
        array("NCCOE", "Coeli AB"),
        array("NCCONO", "Coop Norge AS"),
        array("NCCOOP", "COOP Norge SA"),
        array("NCCOTE", "CombiTel Networks AB"),
        array("NCCPPN", "Corus Packaging Plus, Norway AS"),
        array("NCCPS", "Coeli Power Surge Fund Ltd"),
        array("NCCQG", "CQG"),
        array("NCCRE", "Credit Suisse SEC Europe Ltd."),
        array("NCCSI", "Credit Suisse International"),
        array("NCD", "Hafslund Hedging AS"),
        array("NCDACO", "Danske Commodities AS"),
        array("NCDACO1", "Danske Commodities AS"),
        array("NCDAK", "Dala Kraft AB"),
        array("NCDAL", "Dala Kraft AB"),
        array("NCDALA", "Dala Kraft AB"),
        array("NCDANF", "Danfoss AS"),
        array("NCDAVI", "Vindenergi Danmark amba"),
        array("NCDB", "Deutsche Bank AG London"),
        array("NCDBAS", "Danske Bank A/S"),
        array("NCDES", "D.E. Shaw Plasma Portfolios LLC"),
        array("NCDIS", "Energi Danmark AS"),
        array("NCDIS1", "Energi Danmark AS (UK settlement)"),
        array("NCDIV", "Navitas Power Diversified"),
        array("NCDNB", "DnB Nor Bank ASA"),
        array("NCDNBA", "DnB NOR Bank ASA"),
        array("NCDNBC", "DnB NOR Bank ASA (Collateral bank) UK, London"),
        array("NCDNBS", "DnB - SKM Kraft AS"),
        array("NCDNVE", "Det Norske Veritas Eiendom AS"),
        array("NCDOM", "Domsjö Fabriker AB"),
        array("NCDOMS", "Domstein ASA"),
        array("NCDON", "Dong Naturgas AS"),
        array("NCDON1", "DONG Naturgas AS (UK settlement)"),
        array("NCDONG", "DONG A/S"),
        array("NCDRAM", "Drammen Kommune"),
        array("NCDRAX", "N2EX DF Drax Power Limited"),
        array("NCDS", "Dansk Supermarked A/S"),
        array("NCDSB", "DSB"),
        array("NCDSP", "D.E. Shaw Plasma Portfolios LLC"),
        array("NCDUK", "Duke Energy Intl Finance Ltd"),
        array("NCDUNI", "Duni AB"),
        array("NCDYN", "GAPS Energy AS - 2"),
        array("NCE", "DnB ASA"),
        array("NCE2", "Energi E2 A/S"),
        array("NCEB", "Elbolaget i Norden AB"),
        array("NCECB", "Electrabel Nordic AS"),
        array("NCECO", "E-CO Energi AS"),
        array("NCEDF", "EDF Trading Ltd"),
        array("NCEDFE", "N2EX DF EDF Energy Plc."),
        array("NCEDFU", "EDF Trading Limited"),
        array("NCEE", "Eesti Energia AS"),
        array("NCEEF", "European Energy Fund"),
        array("NCEET", "ENECO Energy Trade"),
        array("NCEEV", "Se EV -Eidsiva Vannkr."),
        array("NCEGE", "ENERGYA VM GESTIÓN DE ENERGÍA S.L.U."),
        array("NCEGL", "Axpo Nordic AS"),
        array("NCEGLAG", "EGL AG (VPP)"),
        array("NCEGLU", "N2EX DF EGL UK Limited"),
        array("NCEIDE", "AS Eidefoss"),
        array("NCEIDO", "Eidsiva Marked AS"),
        array("NCEK", "Energiakolmio Oy"),
        array("NCEKM", "Energi Handel AS"),
        array("NCEKT", "Merrill Lynch Commodities Ltd."),
        array("NCELB", "Electrabel SA"),
        array("NCELBI", "Elbis SP. ZO.O"),
        array("NCELC", "Scandic Energy (gamla Oslo Kraft"),
        array("NCELEC", "Electris Energy Fund Ltd."),
        array("NCELEN", "Elektra Elhandel AS"),
        array("NCELF", "Total Gas & Power Ltd"),
        array("NCELIT", "Elitkraft Sverige AB"),
        array("NCELK", "Elkraft AS"),
        array("NCELKP", "Elkem Power AS"),
        array("NCELNO", "Energa obrot spolka akcynjna"),
        array("NCELP", "El Paso Merchant Energy European"),
        array("NCEM", "EM Finance"),
        array("NCEMH", "Energimidt Handel A/S"),
        array("NCEMHL", "EnergiMidt Handel A/S"),
        array("NCENA", "ENA Energi AB"),
        array("NCENC", "Encatra AS"),
        array("NCENDA", "Energidata AS"),
        array("NCENE", "Energi 1 Nordic AS"),
        array("NCENEL", "Enel Trade SpA"),
        array("NCENET", "Enel Trade S.P.A"),
        array("NCENFY", "Energi Fyn Handel AS"),
        array("NCENKA", "Eramet Norway AS"),
        array("NCENRA", "Verdo Energy AS"),
        array("NCENT", "Enteca AS"),
        array("NCEON", "E.ON Energy Trading SE"),
        array("NCEONF", "Fortum Espoo Oy"),
        array("NCEP", "Alpiq Norway"),
        array("NCERAS", "Erasteel Kloster AB"),
        array("NCERROR", "Used by desken for error trades"),
        array("NCES", "Elsam Kraft AS"),
        array("NCESE", "RWE Supply & Trading Netherlands"),
        array("NCESI", "Essent Trading International VPP"),
        array("NCESK", "Eskilstuna Energi och Miljö AB"),
        array("NCESP", "Eiendomsspar AS"),
        array("NCESPA", "Eiendoms Spar Energi AS"),
        array("NCESTI", "Eesti Energia AS"),
        array("NCETI", "RWE Supply & Trading Switzerland"),
        array("NCETSE", "Etelä-Savon Energia Oy"),
        array("NCEURE", "Eurel AS"),
        array("NCEV", "Eidsiva Vannkraft AS"),
        array("NCEVE", "Evenes Kraftforsyning AS"),
        array("NCEVO", "Evolution Markets Ltd"),
        array("NCF", "Fortum Power and Heat Oy"),
        array("NCF1", "F1 Authorized Trader"),
        array("NCFAFO", "Fastighetsaktiebolaget F."),
        array("NCFALK", "Fallköpings Kommun"),
        array("NCFANI", "Xstrata Nikkelverk AS"),
        array("NCFBAS", "Danske Bank NORWAY"),
        array("NCFCS", "INTL FCSTONE (EUROPE) LTD"),
        array("NCFEED", "FEED USER"),
        array("NCFELL", "Fellesdata AS"),
        array("NCFES", "Fesil AS"),
        array("NCFEX", "FISHEX"),
        array("NCFHC", "N2EX DF First Hydro Company"),
        array("NCFIN", "Fingrid Oyj"),
        array("NCFIRST", "First Line"),
        array("NCFITR", "Fitjar Kraftlag SA"),
        array("NCFJEL", "Fjelberg Kraftlag SA"),
        array("NCFJK", "Fjordkraft AS"),
        array("NCFLAG", "Flagstone International Limited"),
        array("NCFLE", "Flesberg Elektrisitetsverk AS"),
        array("NCFOBA", "ABN AMRO Clearing Bank N.V"),
        array("NCFOCA", "ABN AMRO Clearing Bank N.V"),
        array("NCFOCA1", "Vitol AT (ABN AMRO)"),
        array("NCFOM", "Fortum Markets Oy"),
        array("NCFONL", "Authorized Trader Fortis"),
        array("NCFORB", "Forbrukerkraft AS"),
        array("NCFORS", "Forskningsveien 3 AS"),
        array("NCFORT", "Fortis Bank n.v./s.a."),
        array("NCFRC", "Five Rings Capital LLC"),
        array("NCFREE", "Freepoint Commodities Europe LLP"),
        array("NCFRY", "Frydenlund Eiendom AS"),
        array("NCFUNA", "Celsa Armeringsstål AS"),
        array("NCFUND", "Navitas Power Fundamental"),
        array("NCFY", "Fyrstad Kraft AB"),
        array("NCFYRF", "Fyrfasen Energi AB"),
        array("NCGA", "GASSCO AS"),
        array("NCGALE", "Gallesio Partners AS"),
        array("NCGALL", "Gällivare Kommun"),
        array("NCGASE", "Gaselys"),
        array("NCGAZP", "GAZPROM MARKETING & TRADING LTD."),
        array("NCGBA", "Graflunds Byggnads AB"),
        array("NCGBAB", "Gamla Byn AB"),
        array("NCGBD", "Gudbrandsdal Energi AS"),
        array("NCGCC", "Global Carbon Capital Ltd."),
        array("NCGDFT", "N2EX DF GDF SUEZ Teesside Limited"),
        array("NCGEEL", "Lokalenergi Handel A/S"),
        array("NCGEI", "Geilo Energi Invest AS"),
        array("NCGEIL", "Geilo Energi Invest 2 AS"),
        array("NCGFI", "GFI Brokers Limited"),
        array("NCGK", "G-Kraft AS"),
        array("NCGKR", "G-Kraft AS"),
        array("NCGLOB", "Global Fish AS"),
        array("NCGML", "Griffin Markets Ltd"),
        array("NCGOKO", "Gøtene Kommun"),
        array("NCGOTA", "Göta Energi AB"),
        array("NCGPP", "G.P. Plastindustri Aktiebolag"),
        array("NCGRA", "Graninge Trading AB"),
        array("NCGRY", "Artic Grycksbo Paper AB"),
        array("NCGST", "N2EX DF GDF SUEZ Trading SAS"),
        array("NCGSYN", "IDEELLE A/S"),
        array("NCGUA", "Guardian AS"),
        array("NCGUE", "Gudbrandsdal Energi AS"),
        array("NCGUN", "Gunvor INT. BV Amsterdam"),
        array("NCGYPR", "Gyproc AB"),
        array("NCHAFV", "Hafslund Fjernvarme AS"),
        array("NCHAK", "Haukeland AS"),
        array("NCHAKO", "Hakon Gruppen AS"),
        array("NCHAKU", "Härryda Kommun"),
        array("NCHALM", "Halmstad Kommun"),
        array("NCHAN", "Svenska Handelsbanken AB"),
        array("NCHAUK", "Haugesund Kommune"),
        array("NCHCF", "CBR International Services"),
        array("NCHDBK", "Handelsbanken"),
        array("NCHE", "Hemsedal Energi KF"),
        array("NCHED", "Hedmark Energi Kraft AS"),
        array("NCHEDE", "Hede Nielsen A/S"),
        array("NCHEI", "Heidelberg Cement Norway AS"),
        array("NCHEIS", "HeidelbergCement Sweden AB"),
        array("NCHEKR", "Helgelandskraft AS"),
        array("NCHEL", "Helgelands Kraft AS"),
        array("NCHEOS", "Helse Öst RHF"),
        array("NCHES", "GAPS Energy AS - 3"),
        array("NCHESO", "Helse Sør-Øst RHF"),
        array("NCHEXA", "Hexagon AB"),
        array("NCHFRS", "Håfeström AB"),
        array("NCHHE", "HHE Energi AS"),
        array("NCHI3G", "HI3G Access AB"),
        array("NCHINA", "Hyresbostäder Norrköping AB"),
        array("NCHINK", "Kommunalförbundet Inköp Gävleborg"),
        array("NCHJE", "Hjelmeland Kommune"),
        array("NCHLF", "Helsingfors Energi"),
        array("NCHLK", "Hallingkraft AS"),
        array("NCHLO", "Hålogaland Kraft AS"),
        array("NCHOG", "Höganäs AB"),
        array("NCHOL", "Holta Invest AS"),
        array("NCHREO", "Hamar Regionen Everk Prod. AS 2"),
        array("NCHREP", "Hamar Regionen Everk Prod. AS"),
        array("NCHSBCC", "HSBC Collateral bank UK, London"),
        array("NCHUD", "N2EX DF Hudson Energy Supply UK Limited"),
        array("NCHUR", "Hurum Energiverk"),
        array("NCHURK", "Hurum Kraft AS"),
        array("NCHUS", "Husbyggnadsvaror H.B.V."),
        array("NCHWH", "HWH Energimegling AS"),
        array("NCHY", "Norsk Hydro Produksjon AS"),
        array("NCHYAB", "Hydro Kraft AB"),
        array("NCHYAG", "Hydro Agri AB"),
        array("NCICAP", "ICAP Energy AS"),
        array("NCICAPU", "ICAP Energy Limited"),
        array("NCICM", "Interkraft Capital Managem. AS"),
        array("NCIDEL", "Ideelle A/S"),
        array("NCIE", "Interkraft Energy Fund Ltd."),
        array("NCIHAK", "Hardanger Energi AS"),
        array("NCIHK", "Ishavskraft AS"),
        array("NCIIN", "Iin Energia Oy"),
        array("NCIK", "Istad Kraft AS"),
        array("NCIMAC", "InterKraft MAC 34"),
        array("NCIMAC4", "InterKraft MAC 34"),
        array("NCIMC", "IMC Energy Trading BV"),
        array("NCIMCA", "Imarex Carbon"),
        array("NCIMCE", "IMC Energy Trading BV"),
        array("NCIMP", "Spectron Energy Services AS"),
        array("NCINDUS", "The Industry Ltd"),
        array("NCINEN", "Innovation Energy GMBH"),
        array("NCINK", "Interkraft Trading ASA"),
        array("NCINNO", "Innovative Energy GmbH"),
        array("NCINOR", "Kraftinor AS"),
        array("NCINPO", "N2EX DF IPM Energy Trading Limited"),
        array("NCINTG", "N2EX DF Coryton Energy Company, Ltd."),
        array("NCINTL", "Intelligent Trading"),
        array("NCISK", "Ishavskraft AS"),
        array("NCISOM", "Energiapolar Oy"),
        array("NCISS", "ISS Facility Services AS"),
        array("NCISTR", "Ishavskraft Trading"),
        array("NCJBAS", "Jyske Bank A/S"),
        array("NCJBUG", "J B Ugland Holding AS"),
        array("NCJK", "Jämtkraft AB"),
        array("NCJMFA", "John Mattson Fastighets AB"),
        array("NCJOTU", "Jotunkraft AS"),
        array("NCJPCA", "J.P. Morgan Securities plc"),
        array("NCJPCA1", "J.P. Morgan Securities plc"),
        array("NCJPCA2", "J.P. Morgan Securities plc"),
        array("NCJPCA3", "J.P. Morgan Securities plc"),
        array("NCJPSL", "J.P. Morgan Securities plc"),
        array("NCJPSL1", "J.P. Morgan Securities plc"),
        array("NCJPSL2", "J.P. Morgan Securities plc"),
        array("NCJPSL3", "J.P. Morgan Securities plc"),
        array("NCJPSL4", "J.P. Morgan Securities plc AT"),
        array("NCJPSL5", "J.P. Morgan Securities plc AT"),
        array("NCJPSL8", "J.P. Morgan Securities plc AT"),
        array("NCJPVEC", "JP Morgan Ventures Energy CO"),
        array("NCKAA", "Konsesjonskraftfondet Aust Agder"),
        array("NCKAE", "Kaakon Energia OY"),
        array("NCKAI", "Kainuun Sähkö Oyj"),
        array("NCKAKO", "Kraftkommissionen i Sverige AB"),
        array("NCKALI", "Kalix Kommun"),
        array("NCKARL", "Karlax Pool Aktiebolag"),
        array("NCKARM", "Haugaland Kraft AS Trading"),
        array("NCKASH", "Kraftaktörerna i Sv Sv AB-Hedge"),
        array("NCKAT", "Perhonjoki Oy"),
        array("NCKEE", "Kongsberg Energi Eiendom AS"),
        array("NCKEM", "Kemira Oyj"),
        array("NCKEMA", "Kemanord Kraft AB"),
        array("NCKEMI", "AB Kemisten"),
        array("NCKENO", "KemaNord Kraft Aktiebolag"),
        array("NCKIND", "Kindle Energy AB"),
        array("NCKINV", "Toppen Invest AS"),
        array("NCKIR", "Kirkesundet Kraft AS"),
        array("NCKIR1", "KIRKESUNDE KRAFT AS"),
        array("NCKIRU", "Kirunabostäder AB"),
        array("NCKLK", "Klæbu Kommune"),
        array("NCKOAB", "Korsnäs AB"),
        array("NCKOBU", "Koninklijke Bunge BV"),
        array("NCKOCH", "N2EX DF Koch Commodities Europe Limited"),
        array("NCKOKK", "Kokkolan Energia"),
        array("NCKONG", "Kongsvinger Kommune"),
        array("NCKORP", "Korpelan Voima Kuntayhtymä"),
        array("NCKORT", "Kortlongs AS"),
        array("NCKOT", "Kotkan Energia Oy"),
        array("NCKOTK", "Kotkan Energia Oy"),
        array("NCKR", "KEV Energi AS"),
        array("NCKRIN", "Kraftinvest AS"),
        array("NCKRIS", "Kristiansund Kommune"),
        array("NCKSOY", "Kymenlaakson Sähkö Oy"),
        array("NCKSSO", "KSS Energia Oy"),
        array("NCKUNG", "Kungälvs Kommun"),
        array("NCKUOP", "Kuopion Energia OY"),
        array("NCKVAM", "Kvam Kraftverk AS"),
        array("NCKVEF", "Konsum Värmland Ekonomisk Föreni"),
        array("NCKVIK", "Kvinnherad Kommune"),
        array("NCKVIN", "Kvinnherad Energi AS"),
        array("NCKYM", "UPM Kymmene Oy"),
        array("NCKYP", "Kymppivoima Hankinta Oy"),
        array("NCLABO", "Laboremus Invest AS"),
        array("NCLAC", "Larvik Cell AS"),
        array("NCLAER", "Lærdal Energi AS"),
        array("NCLAH", "Lahti Energia OY"),
        array("NCLANT", "Lantmännen Ek.för."),
        array("NCLAUR", "Laurens Beheer B.V. Neutralco"),
        array("NCLE", "Modity Energy Trading AB"),
        array("NCLECA", "Lehman Brothers International EU"),
        array("NCLEH", "Lehman Brothers International"),
        array("NCLEKO", "Lerums Kommun"),
        array("NCLEXL", "Lexel A/S"),
        array("NCLGE", "Lillehammer og gausdal E-verk AS"),
        array("NCLIDK", "Lidköpings Kommun"),
        array("NCLIE", "Lier Everk AS"),
        array("NCLIER", "LIER EVERK AS"),
        array("NCLIND", "AB Lindex"),
        array("NCLOF", "Lofotkraft Produksjon AS"),
        array("NCLOO", "Lännen Omavoima OY"),
        array("NCLOS", "LOS AS"),
        array("NCLOU", "Castleton Commodities Merchant Europe Sàrl"),
        array("NCLUFT", "Swedavia AB"),
        array("NCLUST", "Luster Energiverk AS"),
        array("NCLYA", "Lyse AS"),
        array("NCLYS", "Lyse Energisalg AS"),
        array("NCM3", "M3 Kraft"),
        array("NCM3C", "M3 Capital AS"),
        array("NCMABO", "Pipelife Norge AS"),
        array("NCMAC", "N2EX DF Macquarie Bank Ltd"),
        array("NCMALV", "Malvik Everk AS"),
        array("NCMAN", "MF Global UK Limited"),
        array("NCMAN-E", "MF Global Execution"),
        array("NCMAN-I", "Man Financial ISV (CQG)"),
        array("NCMAN1", "Vitol NCM"),
        array("NCMANF", "Man Financial"),
        array("NCMASO", "Mäntsälän Sähkö Oy"),
        array("NCMCD", "McDiensten Ekonomisk Förening"),
        array("NCMCDO", "Svenska McDonalds AB"),
        array("NCMEAT", "Swedish Meat Ekonomiska Förening"),
        array("NCMEFE", "Dan Energi AS"),
        array("NCMEK", "Mesta Konsern AS"),
        array("NCMER", "Mercuria Energy Trading SA"),
        array("NCMET", "Metsä Group Fin. Services OY"),
        array("NCMETO", "Metso Oyj"),
        array("NCMETR", "MEM METRO Group Energy Production & Management Sp. z o.o."),
        array("NCMETS", "Metsä Tissue AB"),
        array("NCMIP", "Mo Industripark AS"),
        array("NCMIPI", "MIP Industrikraft AS"),
        array("NCMIR", "Mirant Europe B.V"),
        array("NCMJCO", "MJ Commodities AS"),
        array("NCMK", "Markedskraft AS"),
        array("NCMK1", "Markedskraft AS MK1"),
        array("NCMK2", "Markedskraft AS MK2"),
        array("NCMK3", "Markedskraft AS MK3"),
        array("NCMK4", "Fjellbergkraft/Markedskraft MK4"),
        array("NCMKAB", "Markedskraft AB"),
        array("NCMKBU", "Midt Kraft Buskerud AS"),
        array("NCMKM", "Markedskraft AS - Megling"),
        array("NCMKMM", "MK Online"),
        array("NCMLCE", "Merrill Lynch Commodities Ltd."),
        array("NCMLE", "Mälarenergi AB"),
        array("NCMMATH", "MarketMath Europe AB"),
        array("NCMOE", "Moelven Industrier ASA"),
        array("NCMOFA", "Motope Fastighets AB"),
        array("NCMOKO", "Mjölby Kommun"),
        array("NCMOL", "Mölndal Energi AB"),
        array("NCMOR", "Morgan Stanley Capital Group Inc"),
        array("NCMOTA", "Motala Kommun"),
        array("NCMRFK", "Möre og Romsdal Fylkeskommune"),
        array("NCMTKL", "Midt-Telemark Kraftlag"),
        array("NCN2EXD", "N2EX Default Fund"),
        array("NCNAB", "Nordea Bank AB"),
        array("NCNAM", "NAMMO RAUFOSS"),
        array("NCNAR", "Nordkraft Produksjon AS"),
        array("NCNASA", "Nordlandsbanken ASA"),
        array("NCNAT", "Natixis Commodity Markets ltd."),
        array("NCNAV", "Navita Systems AS"),
        array("NCNBAB", "Nordea Bank AB"),
        array("NCNBEL", "Nordea Bank AB on beh. of Elixir"),
        array("NCNBF", "Nordea Bank Finland"),
        array("NCNBFLB", "Nordea Bank Finland Plc, London"),
        array("NCNBG", "Nordea Bank Germany"),
        array("NCNBNO", "Nordea Bank Norge ASA"),
        array("NCNBNOC", "Nordea Concentration Bank"),
        array("NCNCB", "Nordic Commodity Brokers LTD"),
        array("NCNCF", "Nordic Commodity Fund AB"),
        array("NCNCF1", "Nordic Commodity Fund AB"),
        array("NCNE", "Nordic Energy Oy"),
        array("NCNEA", "Nordisk Energiforvaltning ASA"),
        array("NCNEF", "Nossebro Energi Försäljning AB"),
        array("NCNEFNI", "NEF Nordic Power (SICAV) Ltd."),
        array("NCNEFO", "NE Fondsmæglerselskab A/S"),
        array("NCNEG", "Newedge UK Financial Ltd"),
        array("NCNEG-E", "Newedge Group (UK Branch) EXEC"),
        array("NCNEG1", "Newedge Group (UK Branch)"),
        array("NCNEG2", "Newedge Group (UK Branch)"),
        array("NCNEML", "Nexen Energy Marketing London"),
        array("NCNESA", "NESA EL AS"),
        array("NCNESS", "Nesset Kraft AS"),
        array("NCNEW", "New Trading International SRL"),
        array("NCNEX", "Nexans Iko Sweden AB"),
        array("NCNGRD", "N2EX DF National Grid Electricity Transmission Plc"),
        array("NCNHE", "Norsk Hydro Energie AS"),
        array("NCNIKL", "Niingen Kraftlag AS"),
        array("NCNJEH", "Neas Energy A/S"),
        array("NCNJEH1", "Neas Energy A/S"),
        array("NCNJEH2", "Neas Energy A/S"),
        array("NCNKN", "NORKRING"),
        array("NCNM", "Nordmöre Energiverk AS"),
        array("NCNM1", "Nordmøre Energiverk AS"),
        array("NCNM2", "Nordmøre Energiverk AS"),
        array("NCNMF", "Norwegian Ministry of Finance"),
        array("NCNNK", "SKM Energy Brokers AS"),
        array("NCNNKP", "Norsk Kraftmegling Portefölje"),
        array("NCNNP", "Terminated on 2012-11-19 NEF Nordic Power (SICAV) Ltd"),
        array("NCNO", "A/L Nord-Österdal Kraftlag"),
        array("NCNOAB", "Norden Umbrella Fund Plc"),
        array("NCNOBY", "Nordenfjelske Bykredtt Stiftelse"),
        array("NCNOC", "Noble Clean Fuels Limited"),
        array("NCNOE", "Noe Energi AS"),
        array("NCNOEE", "Noe Energi A/S"),
        array("NCNOEL", "Nordic Elförsörjning AB"),
        array("NCNOF1", "NEF Nordic Power (SICAV) Ltd"),
        array("NCNOF2", "NEF Energy Diversified (SICAV) L"),
        array("NCNOFA", "Nordea Fastigheter AB"),
        array("NCNOME", "Nome Energi AS"),
        array("NCNOP", "Nordic Power Trading F.M.B.A."),
        array("NCNOPT", "NPT A/S"),
        array("NCNORA", "Nora Energi AB"),
        array("NCNORG", "Norgips AS"),
        array("NCNORK", "Norrtälje Kommun"),
        array("NCNORN", "Saint Gobain Ceramic MaterialsAS"),
        array("NCNORW", "NorWatt Energy Invest AS"),
        array("NCNOSCC", "NOS clearinghus broad cast kund"),
        array("NCNOSK", "NOS"),
        array("NCNOVO", "Novo Nordisk AS"),
        array("NCNP", "Nord Pool one - many"),
        array("NCNPBS", "NORW Nordic Power Balanced Strat"),
        array("NCNPC", "Nord Pool own account"),
        array("NCNPCC", "Nord Pool, Carbon copy Cus"),
        array("NCNPFS", "NORW Nordic Power Focused Strat"),
        array("NCNPMPS", "Nord Pool own account MPS"),
        array("NCNPO", "Nordic Power Trading I AS"),
        array("NCNPT", "Nord Pool Trading BUF"),
        array("NCNPX", "Nasdaq OMX Commodities"),
        array("NCNRD", "Nordea Bank Finland Plc"),
        array("NCNRV", "Reitan Convenience AS"),
        array("NCNSI", "Norske Skogindustrier ASA"),
        array("NCNSTE", "Netstep AS"),
        array("NCNTE", "NTE Energi AS"),
        array("NCNTH", "Pareto Commodity AS"),
        array("NCNUMA", "Nurmijärven Sähkö Oy"),
        array("NCNUO", "Vattenfall Netherlands"),
        array("NCNURM", "Nurmijärven Sähkö Oy"),
        array("NCNVJE", "Nordvestjysk Elforsyning"),
        array("NCNVK", "Nordvest Kraft AS"),
        array("NCNVT", "Navitas Capital Management"),
        array("NCODEN", "Odda Energi AS"),
        array("NCOEEV", "Övre Eiker Energi AS"),
        array("NCOH", "Bixia Energy Management AB"),
        array("NCOJEE", "Östjyske Energi Erhverv AS"),
        array("NCOK", "Bixia AB"),
        array("NCOKA", "OK AMBA"),
        array("NCOKAG", "Oesterreichische"),
        array("NCOKFA", "Österlens Kraft Försäljnings AB"),
        array("NCOKO", "Mjoskraft Strom AS"),
        array("NCOLU", "Oulun Energia"),
        array("NCOLY", "Olympia Holding AS"),
        array("NCOM", "Stockholm Clearing Settlement Hub"),
        array("NCOMX", "NASDAQ OMX"),
        array("NCOP", "Oppland Energi AS"),
        array("NCOPLY", "Opplysningsvesenets Fond"),
        array("NCOPPE", "Oppegård Kommune"),
        array("NCORBO", "Örebro Bostäder AB"),
        array("NCORE", "Öresundskraft AB"),
        array("NCORK", "Orkla Finans Comm. Management Pl"),
        array("NCORKA", "Örebro Kartongbruk AB"),
        array("NCORKO", "Örebro Kommun"),
        array("NCORLA", "Örebro Läns Landsting"),
        array("NCORN", "Örnsköldsviks Kommun"),
        array("NCOSKS", "Östfold Energi Kraftsalg AS"),
        array("NCOSLU", "Oslo Lufthavn AS"),
        array("NCOSS", "Keskusosuuskunta Oulun Seudun Sähkö"),
        array("NCOSSK", "Oslo Kommune Skoleteaten"),
        array("NCOST", "Østfold Energi AS"),
        array("NCOSTM", "Østfold Energi AS"),
        array("NCOSTT", "Östfold Energi Prod ASTrading"),
        array("NCOTAB", "Öresundskraft Energy Trading AB"),
        array("NCOVA", "Ovako Hofors AB"),
        array("NCOVI", "Övik Energi AB"),
        array("NCOYS", "Øystre Slidre Kommune"),
        array("NCOZB", "Valartis Bank AG"),
        array("NCPAFU", "Pareto Power Master Fund LTD"),
        array("NCPAG", "Pågengruppen AB"),
        array("NCPAIH", "Päijät-Hämeen Energia Oy"),
        array("NCPAS", "Pasvik Kraft AS"),
        array("NCPB", "Pohjola Bank Plc"),
        array("NCPBPL", "Pohjola Bank Plc"),
        array("NCPD", "Power-Deriva OY"),
        array("NCPEL", "Norway Pelagic"),
        array("NCPES", "Posten Eiendomssenter"),
        array("NCPFPC", "PNC International Bank Limited"),
        array("NCPHIL", "N2EX DF Phillips 66 Trading Limited"),
        array("NCPINK", "Copenhagen Power Invest AS"),
        array("NCPKE", "Poludniowy Koncern Energetyczny"),
        array("NCPKS", "Pohjois-Karjalan Sähkö Oy"),
        array("NCPL", "Göteborg Energi Din EL AB"),
        array("NCPLST", "Pluss Staufer AS"),
        array("NCPOE", "Positive Equity Limited"),
        array("NCPOH", "Pohjolan Voima Oy"),
        array("NCPOKO", "Porsgrunn Kommune"),
        array("NCPORI", "Pori Energia Oy"),
        array("NCPOT", "Powertrade AS"),
        array("NCPOTR", "Powertrade AS"),
        array("NCPOWE", "Powertrade AS"),
        array("NCPPF", "Nordea Bank AB on behalf of PPF"),
        array("NCPPF1", "Nordea Bank AB on behalf of PPF"),
        array("NCPPS", "Plenum Power Surge Ltd"),
        array("NCPRAK", "Praksis Invest Kraft AS"),
        array("NCPREB", "Tullet Prebon (Europe) Limited"),
        array("NCPREL", "PremiEl AS"),
        array("NCPROC", "Procerta Forvaltning AS"),
        array("NCPROG", "Progressio AS"),
        array("NCPROT", "Proton Industries AB"),
        array("NCPUMP", "Pumpøs AS"),
        array("NCQEB", "Quality Energy Brokers"),
        array("NCRAEN", "Rauman Energia Oy"),
        array("NCRAIS", "Raisio Group Plc"),
        array("NCRAO", "RAO Nordic Oy"),
        array("NCRAOAE", "RAO Nordic Oy"),
        array("NCRAUE", "Raufoss Engineering & Service"),
        array("NCRAUK", "Raumakraft Invest AS"),
        array("NCRAUL", "Rauland Kraftforsyningslag"),
        array("NCRAUM", "Rauma Energi AS"),
        array("NCRAVD", "Ravdex AS"),
        array("NCRBS", "The Royal Bank of Scotland PLC"),
        array("NCREL", "Reliant Energy Financial Trading"),
        array("NCRET", "Returkraft AS"),
        array("NCREX", "Rexcell Tissue and Airlaid AB"),
        array("NCRING", "Ringsjö Energi Försäljnings AS"),
        array("NCRISK", "Rissa Kraftlag BA"),
        array("NCRKA", "Rauma Energi Kraft AS"),
        array("NCRKOM", "Ringsaker Kommune"),
        array("NCRKP", "Ringeriks-Kraft Produksjon AS"),
        array("NCROCK", "A/S Rockwool"),
        array("NCRODA", "Rodamco Sverige AB"),
        array("NCROME", "Nedre Romerike Vannverk IKS"),
        array("NCROR", "Röros Elektrisitetsverk A/S"),
        array("NCROTT", "Rottneros AB"),
        array("NCRT", "REN Trading S.A"),
        array("NCRWE", "RWE Supply & Trading GmbH"),
        array("NCRWE1", "RWE Supply & trading Limited"),
        array("NCRWEO", "RWE Trading GmbH - Nordic Option"),
        array("NCS", "Statkraft Energi AS"),
        array("NCS1", "Statkraft AS 1"),
        array("NCS2", "Statkraft AS 2"),
        array("NCS3", "Statkraft AS 3"),
        array("NCSA", "Samkraft AS"),
        array("NCSAM", "Danske Bank Plc"),
        array("NCSAS", "Scandinavian Airlines System"),
        array("NCSAVO", "Savon Voima Oyj"),
        array("NCSBDK", "Sydbank"),
        array("NCSBF", "SEB Finland"),
        array("NCSBP", "DANSKE BANK PLC FINLAND"),
        array("NCSCA", "Scaent AB"),
        array("NCSCAG", "SCA Graphic Sundsvall AB"),
        array("NCSCAH", "Scandic Hotels Holding AB"),
        array("NCSCAM", "Scandem Market AB"),
        array("NCSCAN", "Scania CV AB"),
        array("NCSCEM", "HeidelbergCement Sweden AB"),
        array("NCSCEN", "ScanEnergi AS"),
        array("NCSCHI", "Schibsted ASA"),
        array("NCSE", "Stange Energi AS"),
        array("NCSEA", "SEA Norge"),
        array("NCSEB", "Skandinaviska Enskilda Banken AB"),
        array("NCSEB-E", "Skandinaviska Enskilda B. EXEC"),
        array("NCSEB-I", "SEB Genium Web Trade"),
        array("NCSEB-P", "Skandinaviska Enskilda B. PROP"),
        array("NCSEB-X", "SEB Genium INET View only"),
        array("NCSEB1", "Skandinaviska Enskilda Banken AB"),
        array("NCSEBN", "Skandinaviska EB"),
        array("NCSEC", "Sector Kraft AS"),
        array("NCSECO", "Seco Tools AB"),
        array("NCSELB", "Selbu Energiverk AS"),
        array("NCSEM", "Sempra Energy Europe Ltd"),
        array("NCSENA", "Senaatti-kiinteistöt"),
        array("NCSFAS", "Specialfastigheter Sverige AB"),
        array("NCSFE", "SFE Produksjon AS"),
        array("NCSFEM", "SFE Produksjon AS"),
        array("NCSFEP", "SFE Produksjon AS"),
        array("NCSFOL", "Söndre Follo Energi AS"),
        array("NCSGMBH", "Statkraft Markets GmbH"),
        array("NCSGTL", "Statoil ASA"),
        array("NCSH", "Solheim Energi AS"),
        array("NCSHAB", "Svenska Handelsbanken AB"),
        array("NCSHE", "Shell Energy Europe Limited"),
        array("NCSIEM", "Siemens AS"),
        array("NCSIOO", "Studentsamskipnaden i Oslo og Ak"),
        array("NCSJFD", "Jernhusen AB"),
        array("NCSKAR", "Skara Kommun"),
        array("NCSKE", "Scandem AB"),
        array("NCSKED", "Skedsmo Kommune"),
        array("NCSKEI", "Skeidar AS"),
        array("NCSKF", "Shepherd Energy AB"),
        array("NCSKFB", "Shepherd Energy AB"),
        array("NCSKFO", "Sydkraft AB-Interportfölj SKFÖ"),
        array("NCSKIL", "Skillebekk Energi"),
        array("NCSKKO", "Skien Kommune"),
        array("NCSKMM", "Svensk Kraftmäkling AB"),
        array("NCSKOV", "Skövde Kommun"),
        array("NCSKS", "SKS Produksjon AS"),
        array("NCSKSK", "SKS Kraftsalg AS"),
        array("NCSLF", "Skellefteå Kraft AB"),
        array("NCSLFE", "Skellefteå Kraft Energihandel AB"),
        array("NCSMAE", "N2EX DF SmartestEnergy Limited"),
        array("NCSMEF", "Graninge Småländsk Energi AB"),
        array("NCSMG", "N2EX DF Statkraft Markets GmbH"),
        array("NCSNA", "Sør-Norge Aluminium AS"),
        array("NCSNB", "Schneider Nordic Baltic"),
        array("NCSNE", "Snefonn AS"),
        array("NCSO", "Statoil ASA"),
        array("NCSOCI", "Societe Generale Energie"),
        array("NCSODR", "Södra Skogägarnas Econ. Förening"),
        array("NCSOG", "A/S Sognekraft"),
        array("NCSOGK", "Sognekraft AS"),
        array("NCSOGN", "Sogn og Fjordane Fylkeskommune"),
        array("NCSOL", "Solidus OY"),
        array("NCSOLA", "Södermanlands Läns Landsting"),
        array("NCSORG", "Sörlie Gruppen AS"),
        array("NCSORU", "Sörum Kommune"),
        array("NCSOUM", "S-Voima OY"),
        array("NCSP1", "Sparebank 1 Gruppen AS"),
        array("NCSPAR", "Swedbank AB"),
        array("NCSPDK", "Sparbank"),
        array("NCSPEC", "Spectron Energy Services Limited"),
        array("NCSPNN", "Sparebank 1 Nord-Norge"),
        array("NCSPNO", "Sparebanken Møre"),
        array("NCSPOR", "AS Oslo Sporveier"),
        array("NCSPOW", "Scottish Power Energy Management Limited"),
        array("NCSPOW9", "N2EX DF Scottish Power Energy Management Limited"),
        array("NCSPSE", "SPS Energia Oy"),
        array("NCSPSMN", "SpareBank 1 SMN"),
        array("NCSPSR", "Sparebank 1 SR-Bank"),
        array("NCSPVNO", "Sparbanken Vest"),
        array("NCSSCR", "Statkraft Energi AS"),
        array("NCSSE", "N2EX DF SSE Energy Supply Ltd"),
        array("NCSSS", "Suur-Savon Sähkö Oy"),
        array("NCST", "Station 1 Finland Oy"),
        array("NCSTA", "Stranda Energiverk AS"),
        array("NCSTAD", "Förvaltningsaktieb. Stadsmuren"),
        array("NCSTAN", "Stange Energi AS"),
        array("NCSTEG", "Stena Gotthard AB"),
        array("NCSTEH", "Lyse Produksjon AS"),
        array("NCSTEM", "Stena Metall AB"),
        array("NCSTEN", "Stena Fastigheter AB"),
        array("NCSTFL", "Stadtwerke Flensburg GmbH"),
        array("NCSTK", "Stord Kommune"),
        array("NCSTO", "NP VPP"),
        array("NCSTOK", "Stokke Kommune"),
        array("NCSTRA", "Stranda Energi AS"),
        array("NCSTRB", "Aktiebolaget Strömstadsbyggen"),
        array("NCSTRY", "Stryn Energi AS"),
        array("NCSUKO", "Sundsvalls Kommun"),
        array("NCSUL", "Suldal ELverk KF"),
        array("NCSUN", "SKL PRODUKSJON AS"),
        array("NCSUND", "Sunndal Energi KF"),
        array("NCSUNE", "Sunndal Energi KF"),
        array("NCSUP", "Sunrise Partners L.L.C."),
        array("NCSVAR", "Eastern Norge Svartisen AS"),
        array("NCSVEN", "Svorka Energi AS"),
        array("NCSVK", "Svenska Kraftnät Gasturbiner AB"),
        array("NCSVKR", "Svenska Kraftnät"),
        array("NCSVKS", "Svenska Kraftnät"),
        array("NCSVOR", "Svorka Energi AS"),
        array("NCSVU", "Sunnfjord Energi AS"),
        array("NCSWAB", "Swedbank"),
        array("NCSWE", "Nobina Sverige AB"),
        array("NCSWIA", "Swedwood International AB"),
        array("NCSYD", "E.ON Energihandel Nordic AB"),
        array("NCSYDK", "E.ON Sverige AB"),
        array("NCTAF", "Tafjord Kraftproduksjon AS"),
        array("NCTAMP", "Tampereen Sähkölaitos OY"),
        array("NCTBEL", "Tullett Prebon (Europe) LTD"),
        array("NCTDR", "TrönderEnergi Kraft AS"),
        array("NCTECH", "Navitas Power Technical"),
        array("NCTEK", "Tekniska Verken i Linköping AB"),
        array("NCTELE", "Konsesjonskraftstyret i Telemark"),
        array("NCTELI", "Telinet Energi AS"),
        array("NCTEM", "TrønderEnergi Marked AS"),
        array("NCTERS", "Tersus AS"),
        array("NCTEST", "Test Ltd"),
        array("NCTET", "Technor Energy Trading AS"),
        array("NCTFS", "Tradition Financial Services Ltd"),
        array("NCTFSG", "Tradition Financial Services Gmb"),
        array("NCTI", "Tindra AS"),
        array("NCTIN", "Tinfos AS"),
        array("NCTINN", "Tinn Energi AS"),
        array("NCTKS", "Trondheim Kraft AS"),
        array("NCTLG", "Telge Krafthandel AB"),
        array("NCTLGK", "Telge Kraft AB"),
        array("NCTMA", "Tafjord Marked AS"),
        array("NCTNO", "Telenor Eiendom Holding AS"),
        array("NCTOF", "Tofino Oy"),
        array("NCTOLF", "Ivar Erik Tollefsen"),
        array("NCTOMT", "Huge Fastigheter AB"),
        array("NCTOT", "Total Gas & Power Limited"),
        array("NCTOTE", "Total Energi ASA"),
        array("NCTPORT", "Trayport"),
        array("NCTR", "Trondheim Energiverk Kraft AS"),
        array("NCTREE", "TREE. S.R.L"),
        array("NCTREG", "3G Infrastructure Services AB"),
        array("NCTRI", "Trianel European Energy Trading"),
        array("NCTRIC", "Tricorona AB"),
        array("NCTRO", "Troms Kraft Handel AS"),
        array("NCTUB", "Tudor BVI Global Portfolio Ltd"),
        array("NCTUR", "Oy Turku Energia"),
        array("NCTUR1", "Oy Turku Energia"),
        array("NCTUS", "Tussa Energi AS"),
        array("NCTYRE", "Tyresö Kommun"),
        array("NCTYS", "Aksjeselskapet Tyssefaldene"),
        array("NCUAB", "UAB E energija"),
        array("NCUBS", "UBS Limited"),
        array("NCUBS1", "UBS1 Authorized Trader"),
        array("NCUBS2", "UBS2 Authorized Trader"),
        array("NCUBS3", "UBS3 Authorized Trader"),
        array("NCUEBE", "Umeå Energi Elhandel AB"),
        array("NCUEE", "Umeå Energi Elhandel AB"),
        array("NCULSM", "Ulsmo AS"),
        array("NCUMOE", "Umoe Industri AS"),
        array("NCUNES", "Uste Nes AS"),
        array("NCUPHE", "Uppsalahem AB"),
        array("NCUPKO", "Uppsala Kommun"),
        array("NCUSTE", "Ustekveikja Energi AS"),
        array("NCUVD", "UVDAL Kraftforsynings AS"),
        array("NCVACA", "Varietas Capital AB"),
        array("NCVAL", "Elverket Vallentuna El AB"),
        array("NCVALA", "Värmlands Läns Landsting"),
        array("NCVALD", "Vald Birn Holding A/S"),
        array("NCVALL", "Vallentuna Energi AB"),
        array("NCVAN", "Vantaan Energia OY"),
        array("NCVANE", "Vantaan Energia Oy"),
        array("NCVANI", "OTCex SA"),
        array("NCVANT", "Vanilla Technology"),
        array("NCVAR", "Barents Energi AS"),
        array("NCVASA", "Vaasan Sähkö Oy"),
        array("NCVAST", "Se GOTA"),
        array("NCVAT", "N2EX DF Vattenfall Energy Trading GmbH"),
        array("NCVEGD", "Statens Vegvesen"),
        array("NCVEPR", "Mesta AS"),
        array("NCVETE", "Vest-Telemark Kraftlag AS"),
        array("NCVF", "Vattenfall AB"),
        array("NCVIDA", "Vida AB"),
        array("NCVIO", "Violina AS"),
        array("NCVIS", "Vis AB"),
        array("NCVIT", "Vitol NCM"),
        array("NCVIT9", "N2EX DF Vitol NCM"),
        array("NCVIZ", "VIZ Risk Management"),
        array("NCVK", "Vestfold Kraft Energi AS"),
        array("NCVKSA", "Vestfold Kraft Energi AS - Salg"),
        array("NCVPA", "Test Customer"),
        array("NCVPM", "Vattenfall Power Management AB"),
        array("NCVSAB", "The Absolut Company Aktiebolag"),
        array("NCVSV", "VSV Energiapalvelu Oy"),
        array("NCVSVO", "Vakka-Suomen Voima Oy"),
        array("NCWALL", "Wallenstam NaturEnergi AB"),
        array("NCWIL", "Willhem AB"),
        array("NCYELL", "Yello Strom AB"),
        array("NCZINK", "Zinkgruvan Mining AB"),
        array("ND", "Nordea Markets"),
        array("NDA", "Nordea Bank Danmark A/S"),
        array("NDS", "Nordea Bank AB (publ)"),
        array("NEB", "Sparekassen for Nr. Nebel og Omegn"),
        array("NEO", "Neonet Securities AB"),
        array("NFY", "Nordfyns Bank A/S"),
        array("NIM", "Nordea Investment Management AB, Denmark"),
        array("NIP", "Nomura International Plc"),
        array("NOA", "Nordea Bank Danmark A/S"),
        array("NON", "Nordnet Bank AB"),
        array("NOR", "Nordea Bank AB (publ)"),
        array("NRD", "Nordea Bank Finland Plc"),
        array("NRDE", "Nordea Bank Finland PLC Estonia Bransch"),
        array("NRK", "NORVIK BANKA"),
        array("NRP", "NRP Securities ASA"),
        array("NRS", "Nørresundby Bank A/S"),
        array("NSP", "Nordoya Sparikassi"),
        array("NTF", "Netfonds Bank AS"),
        array("NYB", "Nykredit Bank"),
        array("NYE", "Nyenburgh Holding B.V."),
        array("NYK", "Nykredit A/S"),
        array("OHF", "Pareto Securities Oy"),
        array("OHM", "Pareto Öhman AB"),
        array("OJB", "Østjydsk Bank A/S"),
        array("OOF", "OOF AB"),
        array("OPV", "Optiver VOF"),
        array("ORN", "Orion Securities UAB FMI"),
        array("OSA", "Oslo Børs (2)"),
        array("PAS", "Pareto Securities AS"),
        array("PLA", "RS Platou Markets AS"),
        array("POH", "Pohjola Pankki Oyj"),
        array("PRB", "Citadele Bankas AB"),
        array("PSB", "Pen-Sam Bank A/S"),
        array("RBN", "The Royal Bank of Scotland PLC"),
        array("RDD", "Realkredit Danmark A/S"),
        array("REM", "Remium Nordic AB"),
        array("RGB", "Regionala Investiciju banka"),
        array("RIABLV", "ABLV Bank AS"),
        array("RICTD", "Citadele banka AS"),
        array("RIDNBR", "DNB banka"),
        array("RIHIP", "Hipoteku banka"),
        array("RIIBR", "RSE Internet Broker"),
        array("RIKRA", "Latvijas Krajbanka"),
        array("RIL", "Ringkjøbing Landbobank A/S"),
        array("RILVG", "Latvijas valsts kase"),
        array("RIMUL", "SMP Bank"),
        array("RINLB", "DNB banka"),
        array("RINRK", "NORVIK BANKA"),
        array("RIPRX", "Parex banka"),
        array("RIRGB", "Regionala investiciju banka"),
        array("RIRSE", "NASDAQ OMX Riga"),
        array("RIRTB", "Rietumu Banka"),
        array("RISEBR", "SEB banka"),
        array("RISWBR", "Swedbank, AS"),
        array("RITKB", "Trasta komercbanka"),
        array("RITRA", "GE Money Bank"),
        array("ROS", "Roskilde Bank A/S"),
        array("RSE", "NASDAQ OMX Riga"),
        array("RTB", "Rietumu Banka"),
        array("SAB", "Citigroup Global Markets Limited"),
        array("SAL", "Salling Bank A/S"),
        array("SAX", "Saxo Bank A/S"),
        array("SBI", "Seðlabanki Íslands"),
        array("SBN", "SkandiaBanken AB"),
        array("SEABG", "ABG Sundal Collier Norge ASA"),
        array("SEABR", "ABR Financial B.V"),
        array("SEABRMM", "ABR Financial B.V MM"),
        array("SEABS", "Ålandsbanken Abp"),
        array("SEABSB", "Ålandsbanken Abp"),
        array("SEABSMM", "Ålandsbanken Sverige AB, MM"),
        array("SEAFS", "AFS Equity & Derivatives B.V"),
        array("SEALM", "Alm. Brand Bank A/S"),
        array("SEALO", "ALOC Bonnier A/S (ISV)"),
        array("SEAOI", "All Options International B.V."),
        array("SEAOIMM", "All Options International B.V.MM"),
        array("SEARC", "Arctic Securities ASA"),
        array("SEARG", "Sparebank 1 Markets"),
        array("SEARION", "Arion Custody Services"),
        array("SEAVA", "Avanza Bank AB"),
        array("SEB", "Skandinaviska Enskilda Banken AB"),
        array("SEBGC", "BGC Brokers LP."),
        array("SEBPP", "BNP Paribas Arbitrage, SNC"),
        array("SEBPS", "BNP Paribas Securities Services"),
        array("SEBR", "SEB banka"),
        array("SEBRX", "Barclays Bank Plc"),
        array("SEC", "Carnegie Investment Bank AB"),
        array("SECAR", "Carnegie Investment Bank AB,Finl"),
        array("SECBA", "Carnegie Bank A/S"),
        array("SECBAMM", "Carnegie Bank A/S MM"),
        array("SECBK", "Commerzbank AG"),
        array("SECCM", "Conduit Capital Markets"),
        array("SECDG", "Citadel Deriv. Gr. Europe Ltd"),
        array("SECFE", "Cantor Fitzgerald Europe"),
        array("SECH", "Carnegie Investment Bank AB, House"),
        array("SECMM2", "Carnegie Investment Bank AB, MM2"),
        array("SECMMI", "Carnegie Investment Bank AB, MMI"),
        array("SECMMR", "Carnegie Investment Bank AB, MMR"),
        array("SECO", "Danske Bank Consensus"),
        array("SECQG", "CQG"),
        array("SECSB", "Credit Suisse Securi.EU (HOUSE)"),
        array("SECSBC", "Credit Suisse Securi.EU (CLIENT)"),
        array("SECW1IF", "CW1 for Interface files"),
        array("SEDA", "Danske Bank A/S"),
        array("SEDAMM", "Danske Bank A/S MM"),
        array("SEDBH", "Danske Bank A/S, Helsinki Branch"),
        array("SEDBHMM", "Danske Bank A/S, Helsinki Br MM"),
        array("SEDBL", "Deutsche Bank AG"),
        array("SEDIF", "Saxo Privatbank A/S"),
        array("SEDNM", "DNB Bank ASA"),
        array("SEDNMC", "DNB Bank ASA Custody"),
        array("SEE", "SEB Wealth Management"),
        array("SEEFG", "EFG Bank AB (publ)"),
        array("SEEKF", "Catella Förmögenhetsförvaltning AB"),
        array("SEENS", "Skandinaviska Enskilda Banken AB"),
        array("SEENSMM", "Skandinaviska Ensk. Banken AB MM"),
        array("SEENSMN", "Skandinaviska Ensk. Bank Norge"),
        array("SEEP", "Erik Penser Bankaktiebolag(publ)"),
        array("SEEPMM", "Erik Penser Bankaktiebolag MM"),
        array("SEERS", "Eden Rock Securities Ltd"),
        array("SEEVL", "Evli Bank Abp"),
        array("SEEVLMM", "Evli Bank Abp MM"),
        array("SEEXE", "Execution Noble Limited"),
        array("SEEXN", "Exane Options"),
        array("SEFBN", "ABN AMRO Clearing Bank N.V."),
        array("SEFBNA", "ABN AMRO Clearing Bank N.V. / FBNA"),
        array("SEFFF", "FFastFill (ISV)"),
        array("SEFIM", "FIM Pankki Oy"),
        array("SEFIMC", "FIM Pankki Oy Custody"),
        array("SEFIMMM", "FIM Pankki Oy MM"),
        array("SEFIN", "Sparbanken Finn"),
        array("SEFLW", "Flow Traders B.V."),
        array("SEFMD", "Fidessa Plc"),
        array("SEFRONT", "Front capital system"),
        array("SEFTE", "Reseved for Flowertech C.V."),
        array("SEFXN", "Fixnetix Ltd (ISV)"),
        array("SEGEL", "GETCO Europe Ltd"),
        array("SEGFI", "GFI Securities Limited"),
        array("SEGLB", "Glitnir bank hf. (Iceland)"),
        array("SEGLBMM", "Glitnir bank hf. (Iceland) MM"),
        array("SEGLCT", "Sungard Financial Systems SAS (ISV)"),
        array("SEGRI", "Sparbanken Öresund AB"),
        array("SEGSI", "Goldman Sachs international"),
        array("SEHA", "Carnegie Investment Bank AB/ HQ"),
        array("SEHAMM", "HQ Bankaktiebolag, MM"),
        array("SEHAMM2", "HQ Bankaktiebolag MM2"),
        array("SEHB", "Svenska Handelsbanken AB"),
        array("SEHBFI", "Handelsbanken Fin Branch"),
        array("SEHBMM", "Svenska Handelsbanken AB, MM"),
        array("SEHBMM1", "Svenska Handelsbanken AB, HBMM1"),
        array("SEHBS", "Svenska Handelsbanken AB, CFDA"),
        array("SEHBV", "Svenska Handelsbanken S.kunddepå"),
        array("SEHBVFI", "Handelsbanken Fin Branch"),
        array("SEHBX", "Svenska Handelsbanken AB Fonder"),
        array("SEHCT", "Hardcastle Trading AG"),
        array("SEHCTMM", "Hardcastle Trading AG MM"),
        array("SEHLINK", "HEX OMLINK"),
        array("SEHRT", "Hudson River Trading Europe LTD"),
        array("SEHUM", "Humle Kapitalförvaltning AB"),
        array("SEIAT", "IAT Int. AlgorithmicTrading GmbH"),
        array("SEIMC", "IMC Trading B.V."),
        array("SEIMCMM", "IMC Trading B.V. MM"),
        array("SEISL", "ICAP Securities Limited"),
        array("SEJBD", "JB Drax Honore"),
        array("SEJPM", "J.P. Morgan Securities plc"),
        array("SEKAB", "Ålandsbanken Sverige AB"),
        array("SEKAMM", "Kyte Group Ltd/ Atlantic MM"),
        array("SEKBC", "KBC Bank N.V."),
        array("SEKCMM", "Kyte Group Ltd/ C& R Options MM."),
        array("SEKCMN", "Kyte Group Ltd/ C& R Options MM."),
        array("SEKJMM", "Kyte Group Ltd/ Jay Hawk MM."),
        array("SEKMS", "Kyte Group Ltd/ Market Securities"),
        array("SEKYT", "The Kyte Group Ltd."),
        array("SEKYTA", "Kyte Group Ltd/ KYTA"),
        array("SELCM", "LCM Sweden AB"),
        array("SELCS", "Liquid Capital Securities Ltd"),
        array("SELOMMS", "OMLX Swed Customer (NOX)"),
        array("SEM", "SEB Merchant Banking"),
        array("SEMCM", "Mariana Capital Markets LLP"),
        array("SEMFG", "MF Global UK Limited"),
        array("SEMGD", "Mako Global Derivat. Partn. LLP"),
        array("SEMGF", "Mangold Fondkommission AB"),
        array("SEMLI", "Merrill Lynch International"),
        array("SEMMX", "MMX Trading B.V."),
        array("SEMMXMM", "MMX Trading B.V. MM"),
        array("SEMNT", "Mint Equites Limited"),
        array("SEMSI", "Morgan Stanley & Co, Int. Plc"),
        array("SEMTY", "Virtu Financial Europe, Limited"),
        array("SENB", "Nordea Bank AB, Sverige (publ)"),
        array("SENBN", "Nordea Bank AB, Sverige/Noteriat"),
        array("SENDC", "Nordea Bank Norge Custody"),
        array("SENDN", "Nordea Bank Norge ASA"),
        array("SENDNMM", "Nordea Bank Norge ASA MM"),
        array("SENDS", "Nordea Bank AB (publ)"),
        array("SENDSMM", "Nordea Bank AB (publ) MM"),
        array("SENEO", "NeoNet Securities AB"),
        array("SENEW", "Newedge UK Financial Limited"),
        array("SENOI", "Nomura International Plc"),
        array("SENON", "Nordnet Bank AB"),
        array("SENPC", "Lysåker Clearing Settlement Hub"),
        array("SENRD", "Nordea Bank Finland Plc"),
        array("SENRDC", "Nordea Bank Finland Plc Custody"),
        array("SENRDMM", "Nordea Bank Finland Plc MM"),
        array("SENTF", "Netfonds Bank AS"),
        array("SENYB", "Nykredit Bank A/S, Danmark"),
        array("SENYE", "Nyenburgh Holding B.V."),
        array("SEOHC", "E. Öhman J:or Capital AB"),
        array("SEOHCMM", "E. Öhman J:or Capital AB, MM"),
        array("SEOM", "OM STOCKHOLM"),
        array("SEOMDP", "NASDAQ OMX Direct Pledge Customers"),
        array("SEOMDPD", "NASDAQ OMX Direct Pledge Customers Default Fund"),
        array("SEOMERR", "OM STOCKHOLM"),
        array("SEOMMAK", "OM STOCKHOLM"),
        array("SEOMMM", "OM MARKET MAKER"),
        array("SEOM_GR", "OM INTERNAL"),
        array("SEOPS", "Pohjola Bank plc"),
        array("SEOPV", "Optiver VOF"),
        array("SEOPVMM", "Optiver VOF Market Maker"),
        array("SEOTC", "HPC"),
        array("SEOWB", "IWB N.V."),
        array("SERATMM", "RESEARCH & TRADE AB"),
        array("SERBC", "Reseved for Royal Bank of Canada Europe Ltd"),
        array("SERBG", "The Royal Bank of Scotland plc."),
        array("SEREM", "Remium Nordic AB"),
        array("SERGK", "Riksgäldskontoret"),
        array("SERIX", "Sveriges Riksbank"),
        array("SESAB", "Citigroup Global Markets Ltd"),
        array("SESABC", "Citigroup Global Markets Ltd / SEG Client"),
        array("SESAN", "Banco Santander S.A."),
        array("SESANB", "Banco Santander S.A. PatSystems"),
        array("SESATSM", "Sungard Global Trading (ISV)"),
        array("SESBL", "Sunrise Brokers LLP"),
        array("SESBN", "SkandiaBanken AB"),
        array("SESCR", "Scrocca Option Trading B.V"),
        array("SESE", "Skandinaviska Enskilda Banken AB"),
        array("SESEB", "SEB TREASURY"),
        array("SESEBF", "SEB Futures"),
        array("SESEBL", "SEB LUXEMBURG"),
        array("SESEBO", "Skandinaviska Enskilda Banken AB Oslo"),
        array("SESEBP", "SEB pulp"),
        array("SESEF", "Skandinaviska Ensk.Banken AB SEF"),
        array("SESESL", "SEB STOCK LENDING"),
        array("SESGA", "Saga Investment Bank hf"),
        array("SESGAMM", "Saga Investment Bank hf MM"),
        array("SESGP", "Société Générale SA"),
        array("SESGPMM", "Société Générale SA MM"),
        array("SESHYP", "Stadshypotek AB"),
        array("SESI", "SV HANDELSBANKEN LONDON BRANCH"),
        array("SESIG", "Susquehanna International Group Ltd"),
        array("SESIGMM", "Susquehanna International Group Ltd MM"),
        array("SESNB", "Spar Nord Bank A/S (Clearing only)"),
        array("SESOC", "Source Capital AG"),
        array("SESP", "Swedbank AB"),
        array("SESPCUS", "Swedbank AB SPCUST"),
        array("SESPI", "SPARBANKEN SVERIGE AB SPI"),
        array("SESPMM", "Swedbank AB MM"),
        array("SESPMMA", "Swedbank AB (publ) MMA"),
        array("SESPMMI", "Swedbank AB (publ) MMI"),
        array("SESPMMN", "Swedbank AB (publ) MMN"),
        array("SESPMMR", "Swedbank AB (publ MM Bond Future"),
        array("SESPMMW", "Swedbank AB (publ) MMW"),
        array("SESPN", "Swedbank AB (publ) CUSTODY"),
        array("SESRE", "Spire Europe Limited"),
        array("SESREA", "Spire Europe Limited (A)"),
        array("SESREB", "Spire Europe Limited (B)"),
        array("SESREMM", "Spire Europe Limited MM"),
        array("SESRN", "ION Trading for vector files (ISV)"),
        array("SESS", "SE BANKEN TREASURY"),
        array("SESSUNG", "Sungard - S/W house"),
        array("SESSY", "Sparbanken Syd"),
        array("SESUNG", "Sungard GMI (ISV)"),
        array("SESYD", "Sydbank A/S"),
        array("SETAV", "Tavira Securities Ltd"),
        array("SETBRMM", "Tibra Trading Europe Ltd. MM"),
        array("SETFS", "TFS Derivatives Ltd"),
        array("SETMB", "Timber Hill (Europe) AG"),
        array("SETMBM1", "Timber Hill (Europe) AG MM"),
        array("SETMBMM", "Timber Hill (Europe) AG MM"),
        array("SETSP", "Tradition Securities and Futures"),
        array("SETSTM1", "TEST M1"),
        array("SEUBS", "UBS Limited"),
        array("SEUNI", "Nordea Bank Danmark A/S"),
        array("SEUNIMM", "Nordea Bank Danmark / MMB"),
        array("SEVCM", "Vantage Capital Markets LLP"),
        array("SEVFI", "Virtu Financial Ireland Limited"),
        array("SEVPA", "OMX Broker Services AB"),
        array("SEVPCGW", "VPC GATEWAY"),
        array("SEWEB", "WEBB Traders B.V."),
        array("SEWOL", "Wolverine Trading UK Limited"),
        array("SEWOLMM", "Wolverine Trading UK Limited MM"),
        array("SEXBZ", "XBZ Limited"),
        array("SEÖ", "Pareto Öhman AB"),
        array("SEÖF", "Pareto Öhman AB Finland"),
        array("SEÖMM", "Pareto Öhman AB MM"),
        array("SEÖSPEC", "PARETO ÖHMAN AB SPECIAL"),
        array("SGL", "Société Générale S.A."),
        array("SGP", "Société Générale S.A."),
        array("SHB", "Svenska Handelsbanken AB"),
        array("SHD", "Svenska Handelsbanken AB"),
        array("SIS", "Susquehanna International Securities Ltd"),
        array("SKA", "Sparekassen i Skals"),
        array("SKJ", "Skjern Bank A/S"),
        array("SLB", "Siauliu Bankas AB"),
        array("SNB", "Spar Nord Bankaktieselskab"),
        array("SO", "Sparebank 1 Nord Norge Securities"),
        array("SPA", "Sparinvest Fondsmæglerselskab A/S"),
        array("SPF", "Sparekassen Faaborg"),
        array("SPLO", "Sparekassen Lolland A/S"),
        array("SPM", "Middelfart Sparekasse"),
        array("SPSJ", "Sparekassen Sjælland A/S"),
        array("SPV", "Sparekassen Sjælland"),
        array("SRE", "Spire Europe Limited"),
        array("SSE", "Nasdaq OMX Stockholm"),
        array("STABS", "Ålandsbanken Sverige AB"),
        array("STARC", "Arctic Securities ASA"),
        array("STAVA", "Avanza Bank AB"),
        array("STBPP", "BNP Paribas Arbitrage SNC"),
        array("STBRX", "Barclays Bank PLC"),
        array("STBYR", "Byr sparisjóður"),
        array("STCAD", "Carnegie Investment Bank AB"),
        array("STCAR", "Carnegie Investment Bank AB"),
        array("STCIC", "Marketprizm"),
        array("STCON", "Danske Consensus"),
        array("STCSA", "Christiania Securities ASA"),
        array("STDBL", "Deutsche Bank AG"),
        array("STDDE", "Hembanken"),
        array("STDNM", "DNB Bank ASA"),
        array("STEPB", "Erik Penser Bankaktiebolag"),
        array("STFBK", "BankNordik P/F"),
        array("STFOF", "Fondsfinans ASA"),
        array("STGLT", "GL TRADE SA"),
        array("STGTM", "Garantum Fondkommission AB"),
        array("STHFV", "H.F. Verðbréf hf."),
        array("STISB", "Íslandsbanki hf."),
        array("STJVB", "Jöklar-Verðbréf hf."),
        array("STKAU", "Arion banki hf."),
        array("STLAI", "Landsbankinn hf."),
        array("STLFB", "Länsförsäkringar Bank AB"),
        array("STMEG", "Virðing hf."),
        array("STMGF", "Mangold Fondkommission AB"),
        array("STMPB", "MP Banki hf."),
        array("STNDS", "Nordea Bank AB (publ)"),
        array("STNEO", "Neonet Securities AB"),
        array("STNON", "Nordnet Bank AB"),
        array("STNOR", "Nordea Bank AB (publ)"),
        array("STOHM", "Öhman J:or Fondkommission AB, E."),
        array("STOM11", "SaxTat"),
        array("STOM12", "TRAXESS"),
        array("STQTH", "Quanthouse"),
        array("STR", "Straumur fjárfestingabanki hf."),
        array("STRAT", "Research & Trade"),
        array("STRBG", "The Royal Bank of Scotland PLC"),
        array("STREM", "Remium Nordic AB"),
        array("STRGK", "Riksgäldskontoret"),
        array("STSAB", "Citigroup Global Markets Limited"),
        array("STSBI", "Seðlabanki Íslands"),
        array("STSBN", "SkandiaBanken AB"),
        array("STSEB", "Skandinaviska Enskilda Banken AB"),
        array("STSGA", "Saga fjárfestingarbanki hf."),
        array("STSHB", "Svenska Handelsbanken AB"),
        array("STSHD", "Svenska Handelsbanken AB"),
        array("STSTO", "NASDAQ OMX Stockholm Fixed Income"),
        array("STSWB", "Swedbank AB"),
        array("STSWD", "Swedbank AB."),
        array("STTEM", "Terra Markets AS"),
        array("STTIN", "Tindar Verdbref hf."),
        array("STVEI", "Teris"),
        array("STVPA", "VPA, Värdepappersadministration AB"),
        array("STVPC", "Euroclear Sweden AB"),
        array("SVB", "Svenska Handelsbanken (filial)"),
        array("SVS", "Svendborg Sparekasse"),
        array("SWB", "Swedbank AB"),
        array("SWBR", "Swedbank, AS"),
        array("SWBT", "Swedbank AS"),
        array("SWBV", "Swedbank, AB"),
        array("SWD", "Swedbank AB."),
        array("SYD", "Sydbank A/S"),
        array("TACRE", "Cresco Väärtpaberid"),
        array("TADDBE", "Danske Bank A/S Eesti filiaal"),
        array("TALHV", "LHV Pank AS"),
        array("TAMRF", "Terminated on 2012-07-02 Versobank AS"),
        array("TAP", "Tapiola Bank Ltd"),
        array("TASWBT", "Swedbank AS"),
        array("TATSE", "NASDAQ OMX Tallinn"),
        array("TAYHI", "SEB Pank AS"),
        array("THY", "Sparekassen Thy"),
        array("TKB", "Trasta komercbanka"),
        array("TMB", "Timber Hill Europe AG"),
        array("TND", "Tønder Bank A/S"),
        array("TOK", "Totalkredit Realkreditfond"),
        array("TOT", "Totalbanken A/S"),
        array("TRA", "GE Money Bank"),
        array("TSE", "NASDAQ OMX Tallinn"),
        array("TTAACB1", "AACB1"),
        array("TTABR", "ABR Financial B.V"),
        array("TTALEX", "Alex"),
        array("TTALL", "All Options"),
        array("TTATG", "Algorithmic Trading Group"),
        array("TTBBB", "Binck Bank Belgium"),
        array("TTBBF", "Binck Bank France"),
        array("TTBBFSR", "Binck Bank France SRD"),
        array("TTBBN", "Binck Bank Netherlands"),
        array("TTBFRNK", "Be Frank"),
        array("TTBIT", "Binck Bank Italy"),
        array("TTDBNLE", "Deutsche Bank NL"),
        array("TTDRIE", "323 Trading"),
        array("TTEX", "Instinet"),
        array("TTFBGC", "Fortis Bank Global Clearing"),
        array("TTFRIES", "Friesland Bank"),
        array("TTHCH", "Holland Clearing House"),
        array("TTIMC", "IMC Trading B.V."),
        array("TTMTY", "Virtu Financial Ireland Ltd."),
        array("TTOPT", "Optiver"),
        array("TTQUOD", "Quod Financial"),
        array("TTSCR", "Scrocca"),
        array("TTSNSD", "SNSD"),
        array("TTSNSE", "SNSE"),
        array("TTTIBRA", "Tibra Trading"),
        array("TTTICK", "TICK TS"),
        array("TTTOM", "TOM"),
        array("TTTTMM", "TOM Trading, Market Operations"),
        array("UB", "UB Securities Ltd"),
        array("UBS", "UBS Limited"),
        array("UBSR", "UBS Limited"),
        array("UKB", "Ukio Bankas AB"),
        array("UKR", "Unikredit Realkreditaktieselskab"),
        array("UOC", "Unidentified off-exchange counterparty"),
        array("VEF", "Vestfyns Bank A/S"),
        array("VES", "Sparbank"),
        array("VFI", "Virtu Financial Ireland Limited"),
        array("VHS", "Vorbasse Hejsnvig Sparekasse"),
        array("VIDDBL", "Danske Bank A/S Lietuvos filialas"),
        array("VIDNBV", "DnB Bankas AB"),
        array("VIFBI", "Bankas Finasta AB"),
        array("VIFNB", "Finbaltus FMI UAB"),
        array("VIFNS", "Finasta FMI AB"),
        array("VILTG", "Lietuvos Respublikos Vyriausybe"),
        array("VIMPBB", "EA fjárfestingarfélag hf."),
        array("VIN", "Vinderup Bank A/S"),
        array("VINDL", "DnB Bankas AB"),
        array("VIORN", "Orion Securities UAB FMI"),
        array("VIPRB", "Citadele Bankas AB"),
        array("VISLB", "Siauliu Bankas AB"),
        array("VISWBV", "Swedbank, AB"),
        array("VIUKB", "Ukio Bankas AB"),
        array("VIVLB", "SEB Bankas AB"),
        array("VIVSE", "NASDAQ OMX Vilnius"),
        array("VJB", "Vestjysk Bank A/S"),
        array("VLB", "SEB Bankas AB"),
        array("VOR", "Vordingborg Bank A/S"),
        array("VP", "VP Securities A/S"),
        array("VPC", "Euroclear Sweden AB"),
        array("VRA", "Sparekassen Vendsyssel"),
        array("VSE", "NASDAQ OMX Vilnius"),
        array("WEB", "Webb Traders B.V"),
        array("WLV", "Wolverine Trading UK Ltd"),
        array("WSL", "Winterflood Securities Ltd"),
        array("XAA", "Aarhus Lokalbank Aktieselskab"),
        array("XFA", "Faster Andelskasse"),
        array("XFK", "Andelskassen Fælleskassen"),
        array("XLK", "Lunde-Kvong Andelskasse"),
        array("XLR", "LR Realkredit A/S"),
        array("YHI", "SEB Pank AS"),
        array("_SUP", "NOC Internal Support")
       ); 
